name: CI
on: push

jobs:
  ci:
    name: Type Checking, Linting
    runs-on: ubuntu-latest
    timeout-minutes: 30
    # TODO: Update environment variables with your own database credentials
    env:
      PGHOST: localhost
      PGDATABASE: expo_example
      PGUSERNAME: expo_example
      PGPASSWORD: expo_example
    steps:
      - name: Start preinstalled PostgreSQL on Ubuntu
        run: |
          sudo systemctl start postgresql.service
          pg_isready
      - name: Create database user
        run: |
          sudo -u postgres psql --command="CREATE USER $PGUSERNAME PASSWORD '$PGPASSWORD'" --command="\du"
      - name: Create database and allow user
        run: |
          sudo -u postgres createdb --owner=$PGUSERNAME $PGDATABASE

      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v4

      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 'lts/*'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Run database migrations
        run: pnpm migrate up

      - name: Generate Expo types
        run: pnpm expo customize tsconfig.json

      - name: Check TypeScript Types
        run: pnpm tsc

      - name: Lint with ESLint
        run: pnpm eslint . --max-warnings 0
